### ISSUE TITLE
⇅ unicode characters not displayed properly

### ISSUE THREAD

**Issue by alicektx** [p-e-w/hegemon#19]
Hi, under mate-terminal, 
the ⇅ characters sadly appear garbled & overlapping:
![tofu](https://user-images.githubusercontent.com/28889624/71976939-48350d00-3220-11ea-8199-b233c3c0848c.png)

Was able to work around it, 
by replacing as follows in model.rs the two instances of:
-MenuItem::new("\u{1F805}\u{1F807}", "Select"),
+MenuItem::new("\u{21C5}", "Select"),
![21C5](https://user-images.githubusercontent.com/28889624/71976947-4d925780-3220-11ea-83b6-3d010de99432.png)

Hopefully the above helps / sheds some light as to why this happens?

All the best

**Comment by p-e-w** [comment]
Your font is missing those glyphs, this has nothing to do with the terminal. What font are you using?

I am aware of the character `21C5`, but while in principle that is exactly the symbol we want here, some fonts render it wider than a single cell despite being "monospaced", causing alignment issues.

**Comment by alicektx** [comment]
Doh! And of course it was _that_ simple... 

'_Monospace Regular 12_' in Preferences... 
fc-match Monospace
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
[https://www.fileformat.info/info/unicode/font/dejavu_sans_mono/list.htm](https://www.fileformat.info/info/unicode/font/dejavu_sans_mono/list.htm)

Had never fiddled with the terminal's 'default' font settings,
ie. say by using exotic fonts or similar, 
hence this really didn't crossed my mind...
Deeply sorry for wasting your time above. :worried:
All the best!
